### ISSUE TITLE
Handling Large Number of Gene IDs in RNAseq Analysis: NCBI Server Timeout

### ISSUE THREAD

**Issue by MauriAndresMU1313** [jdieramon/refseqR#12]
I'm trying to annotate all my unknown genes in my RNAseq analysis. So, my idea was to extract all the ```LOCxxxxxxxxx```, where x is any number, the length of this list of unknown genes is around 13 thousand. 
When I try to find the corresponding protein ID associated with that gene ID, the line:
```
transcript <- refseqR::refseq_fromGene(unknown.genes.list, sequence = "transcript")
```
gave me the following error:
```
NCBI servers are busy. Please try again a bit later.
```
So, I tried to check if with a small list of genes I could do something, for this I did a subset of 50 elements per list. Even with 10, it is not working.
However, I got the same error.
What can I do to handle a large amount of gene IDs?
Any suggestion?

**Comment by jdieramon** [comment]
That's the standard error that occurs when excessive service calls or requests from a single access node exceed the NCBI API's limit on requests per second. See [this](https://www.ncbi.nlm.nih.gov/books/NBK25497/#chapter2.Usage_Guidelines_and_Requiremen). Your idea of splitting your request into multiple calls is very good and should work. You can also try making the calls either on weekends or between 9:00 PM and 5:00 AM Eastern time during weekdays. In any case, it should definitely work with 10 elements. Please provide me 10 items as examples, so I can try to see what's going on.

**Comment by RMSlab** [comment]
Thank you for your quick response. Even if use a ENTREZ API Key, the issue is not solved (with 10 and 50 elements).
This is the line fir the key:
```
set_entrez_key("XXXXXXXXXXXX")
Sys.getenv("ENTREZ_KEY")
```
Let me show you my list:
```
> unknown.genes.subset
[[1]]
[1] "LOC101669871"
[[2]]
[1] "LOC101669883"
[[3]]
[1] "LOC101669887"
[[4]]
[1] "LOC101669892"
[[5]]
[1] "LOC101669908"
[[6]]
[1] "LOC101669919"
[[7]]
[1] "LOC101669923"
[[8]]
[1] "LOC101669926"
[[9]]
[1] "LOC101669937"
[[10]]
[1] "LOC101669947"
```
Then, the same line:
```
transcript <- refseqR::refseq_fromGene(unknown.genes.list, sequence = "transcript")
```
Message:
```
NCBI servers are busy. Please try again a bit later.
```
Any idea? or alternative?

**Comment by jdieramon** [comment]
It looks like you're using a list as the input object. In refseqR, the input is typically a character string. For the function you mentioned, refseq_fromGene, the first argument should be a character string representing the GeneID.
```{r}
locs <-  c("LOC101669871", "LOC101669883", "LOC101669887", "LOC101669892", "LOC101669908", 
     "LOC101669919", "LOC101669923", "LOC101669926", "LOC101669937", "LOC101669947") `
     
sapply(locs, function(x) refseq_fromGene (x, sequence = "transcript"), USE.NAMES = FALSE)
````


```{r}
[[1]]
[1] "XR_198459"

[[2]]
[1] "XM_004765651"

[[3]]
[1] "XR_001181988"

[[4]]
[1] "XM_004746765"

[[5]]
[1] "XM_013047473" "XM_045086619" "XM_004775810" "XM_004775809"

[[6]]
[1] "XM_045073333"

[[7]]
[1] "XM_013049797"

[[8]]
[1] "XM_004780931"

[[9]]
[1] "XM_004782252"

[[10]]
[1] "XM_004761866"
```

**Comment by MauriAndresMU1313** [comment]
Great! Now is working, my bad, I did not realize about the issue with my approach.
However, I got the warning message ```NCBI servers are busy. Please try again a bit later.``` Before I close this solved issue, do you have any advice for the Entrez key? 
I set using 
```
set_entrez_key("XXXXXXXXXXXX")
Sys.getenv("ENTREZ_KEY")
```
As well as, in my 
```
.Renviron file
```
Do you have any suggestion?

**Comment by MauriAndresMU1313** [comment]
I couldn’t solve the issue with the ```NCBI API Key``` (specific issue), so I decided to set a rate limit at a minimum of 3 requests per second. I ran the process in batches and successfully obtained the data I needed. I will close the issue, as ```spapply``` was the key to continuing with the process.
Thank you for your time and for providing the tool!

**Comment by MauriAndresMU1313** [comment]
I couldn’t solve the issue with the ```NCBI API Key``` (specific issue), so I decided to set a rate limit at a minimum of 3 requests per second. I ran the process in batches and successfully obtained the data I needed. I will close the issue, as ```spapply``` was the key to continuing with the process.
Thank you for your time and for providing the tool!
